name: E2E Tests & Update Web Service
on:
   workflow_call:
      inputs:
         ref:
            type: string
            default: ${{ github.ref }}
   
jobs:
   e2etests:
      name: Test
      runs-on: ubuntu-latest
      env:
         CYPRESS_RESPONSE_TIMEOUT: 200000
         CYPRESS_DEFAULT_COMMAND_TIMEOUT: 30000
         CYPRESS_RETRIES: 2
      strategy:
         matrix:
            include:
               - branch: develop
                 webpack: dev
               - branch: master
                 webpack: update
      steps:
         - uses: actions/checkout@v3
           with:
              path: plugins/plugin_ABDesigner
              ref: ${{ inputs.ref }}

         - uses: actions/checkout@v3
           with:
              path: web
              repository: digi-serve/ab_service_web
              token: ${{ secrets.DS_REPO_PAT }}
              ref: ${{ matrix.branch }}

         - run: npm i
           working-directory: plugins/plugin_ABDesigner
         - name: Webpack
           run: npm run build:${{ matrix.webpack }}
           working-directory: plugins/plugin_ABDesigner

        # webpack expects the folder to be called "web" ab-install action expects "ab_service_web"
         - run: mv web ab_service_web
         - uses: digi-serve/ab-install-action@v1
           with:
              port: 8080
              folder: ab
              repository: digi-serve/ab_service_web
              
         - name: Check out kitchen-sink tests
           uses: actions/checkout@v2
           with:
              repository: digi-serve/kitchensink_app
              path: ab/test/e2e/cypress/e2e/kitchensink_app

         # These next steps are to save our ablogs to file
         - run: npm install pm2@latest -g
         - name: Save Logs
           run: pm2 start ./logs.js -- --toFile logs/ABServices.log
           working-directory: ./ab

         - name: Wait for AB
           uses: ifaxity/wait-on-action@v1
           with:
              resource: http://localhost:8080
              timeout: 300000

         - name: Run Cypress Tests
           run: npm run test:e2e:ab-designer -- --browser chrome
           working-directory: ./ab
              
         - uses: actions/upload-artifact@v2
           if: failure()
           with:
              name: cypress-screenshots
              path: ./ab/test/e2e/cypress/screenshots

         - uses: actions/upload-artifact@v2
           if: failure()
           with:
              name: ABServices.log
              path: ./ab/logs/ABServices.log
