name: Merging Rules
on:
   # Run on pull requests into the #master branch
   pull_request:
      branches: [master]

jobs:
   e2e-tests:
      uses: ./.github/workflows/e2e-test.yml
      secrets:
         TOKEN: ${{ secrets.PAT }}
